<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE users[
    <!ELEMENT users (user*)>
    <!ELEMENT user (firstName, lastName, message, company, email)>
    <!ELEMENT firstName (#PCDATA)>
    <!ELEMENT lastName (#PCDATA)>
    <!ELEMENT message (#PCDATA)>
    <!ELEMENT company (#PCDATA)>
    <!ELEMENT email (#PCDATA)>
]>
<users>
    <user>
        <firstName>Nemanja</firstName>
        <lastName>Kasanov</lastName>
        <message>This is the message this user sent.</message>
        <company>Google</company>
        <email>nemanja@gmail.com</email>
    </user>
    <user>
        <firstName>Nikola</firstName>
        <lastName>Ciganovic</lastName>
        <message>This is the message this user sent.</message>
        <company>Facebook</company>
        <email>nikola@gmail.com</email>
    </user>
</users>